# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: FARIS NAZARI
email: your-email@domain.com
author: Faris Nazari
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Faris Nazari. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/farisnazari20
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: Blog
    url: 
  - title: SIF
    url: //sif.uin-suska.ac.id
  - title: UIN
    url: //uin-suska.ac.id
